[package]
name = "sweet_async_aws"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config.workspace = true
aws-sdk-autoscaling.workspace = true
aws-sdk-ec2.workspace = true
aws-sdk-lambda.workspace = true
sweet_async_api = { version = "0.1.0", path = "../api" }
