name = "cyrup-ai"
description = "Zola theme for Cyrup.ai docs"
license = "MIT"
homepage = "https://github.com/mattimustang/zola-grayscale"
min_version = "0.19.0"
demo = "https://mattimustang.github.io/zola-grayscale/"

[author]
name = "Matthew Flanagan"
homepage = "https://github.com/mattimustang"

[original]
author = "Start Bootstrap"
homepage = "https://startbootstrap.com/themes/grayscale/"
repo = "https://github.com/StartBootstrap/startbootstrap-grayscale"
