[package]
name = "sweet_async_aws"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.6.3"
aws-sdk-autoscaling = "1.80"
aws-sdk-ec2 = "1.136"
aws-sdk-lambda = "1.82.0"
sweet_async_api = { path = "../api" }
