# Configuration for nightly rustdoc features
# This requires using cargo +nightly

# Configure external documentation links
[doc.extern-map.registries]
crates-io = "https://docs.rs/"

# Maps for standard library documentation
[doc.extern-map]
std = "https://doc.rust-lang.org/nightly/"
core = "https://doc.rust-lang.org/nightly/core/"
alloc = "https://doc.rust-lang.org/nightly/alloc/"

# Rustdoc flags for feature enablement
[unstable]
rustdoc-scrape-examples = true
rustdoc-map = true

# Nextest configuration
[target.'cfg(all())']
runner = "cargo nextest run --"

# Command examples:
# Generate HTML docs with all features:
# cargo +nightly doc --no-deps -Z unstable-options -Z rustdoc-map -Z rustdoc-scrape-examples
# 
# Generate JSON docs (will be default with this config):
# cargo +nightly doc --no-deps -Z unstable-options -Z rustdoc-map -Z rustdoc-scrape-examples --output-format json
