[package]
name = "sweet_async_spin"
version = "0.1.0"
edition = "2024"

[dependencies]
spin-sdk.workspace = {git = "https://github.com/spin/spin-sdk"}
sweet_async_api = { path = "../sweet-async-api" }
